# Generated by Django 2.0 on 2018-04-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Radioitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_name', models.CharField(max_length=15, unique=True, verbose_name='Название')),
                ('radio_description', models.TextField(verbose_name='Описание радиостанции')),
                ('radio_flow', models.URLField(blank=True, null=True, verbose_name='Ссылка на поток')),
                ('radio_logo', models.ImageField(blank=True, upload_to='logo', verbose_name='Лого Радиостанции')),
                ('radio_logo_link', models.URLField(blank=True, default='http://degur-service.ru/img/p/ru-default-large_default.jpg', verbose_name='Ссылка на изображение')),
                ('radio_view', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('radio_likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Редактирован')),
                ('radio_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Радиостанция',
                'verbose_name_plural': 'Радиостанции',
                'db_table': 'Radioitem',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('info', models.TextField(verbose_name='Информация о жанре')),
                ('popular', models.BooleanField(default=False, verbose_name='Популярный')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'Style',
            },
        ),
        migrations.AddField(
            model_name='radioitem',
            name='radio_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Style', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Country', verbose_name='Страна'),
        ),
    ]
