# Generated by Django 2.0 on 2018-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioitem',
            name='radio_logo_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
    ]
