# Generated by Django 2.0 on 2018-04-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20180416_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='radioitem',
            name='radio_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='radioitem',
            name='radio_error',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='radio.Error_radio', verbose_name='Ошибки'),
        ),
    ]
