# Generated by Django 2.0 on 2018-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20180418_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioitem',
            name='radio_error',
            field=models.BooleanField(default=False, verbose_name='Ошибки'),
        ),
        migrations.DeleteModel(
            name='Error_radio',
        ),
    ]
