# Generated by Django 2.0 on 2018-04-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20180418_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('visible', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='radioitem',
            name='radio_error',
            field=models.BooleanField(default=False, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='comment',
            name='radiostation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='radio.Radioitem', verbose_name='Радиостанция'),
        ),
    ]
