# Generated by Django 2.0 on 2018-04-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_auto_20180419_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
